---
Name: ai-refine
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverstripeLtd\AiRefine\Extensions\RefineSiteTreeExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverstripeLtd\AiRefine\Extensions\RefineSiteConfigExtension

SilverstripeLtd\AiRefine\Services\RefineCheckRateLimiter:
  max_requests: 10
  window_seconds: 300

SilverStripe\Control\Director:
  rules:
    'admin/ai-refine': SilverstripeLtd\AiRefine\Controllers\RefineController

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    'silverstripeltd/ai-refine:client/dist/js/bundle.js':
      defer: true
  extra_requirements_css:
    - 'silverstripeltd/ai-refine:client/dist/styles/bundle.css'
